import Utilitarios.conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class frmCadastroForne extends javax.swing.JFrame {
    conexao con_forne;
    
    
    public frmCadastroForne() {
        initComponents();
         con_forne = new conexao();
        con_forne.conecta();
        con_forne.executaSQL("select * from tbfornecedores order by codigo");
        posicionarRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cod = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        End = new javax.swing.JLabel();
        Cidad = new javax.swing.JLabel();
        Bairr = new javax.swing.JLabel();
        Estad = new javax.swing.JLabel();
        Tele = new javax.swing.JLabel();
        Ema = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Fornecedores");
        setMinimumSize(new java.awt.Dimension(824, 558));
        getContentPane().setLayout(null);

        cod.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cod.setForeground(new java.awt.Color(255, 255, 255));
        cod.setText("Código:");
        getContentPane().add(cod);
        cod.setBounds(230, 140, 50, 17);

        Name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Nome:");
        getContentPane().add(Name);
        Name.setBounds(240, 170, 40, 17);

        Date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Data Nascimento:");
        getContentPane().add(Date);
        Date.setBounds(170, 200, 120, 17);

        End.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        End.setForeground(new java.awt.Color(255, 255, 255));
        End.setText("Endereço:");
        getContentPane().add(End);
        End.setBounds(220, 230, 70, 17);

        Cidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cidad.setForeground(new java.awt.Color(255, 255, 255));
        Cidad.setText("Cidade:");
        getContentPane().add(Cidad);
        Cidad.setBounds(220, 290, 60, 17);

        Bairr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Bairr.setForeground(new java.awt.Color(255, 255, 255));
        Bairr.setText("Bairro:");
        getContentPane().add(Bairr);
        Bairr.setBounds(220, 260, 60, 17);

        Estad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Estad.setForeground(new java.awt.Color(255, 255, 255));
        Estad.setText("Estado:");
        getContentPane().add(Estad);
        Estad.setBounds(220, 320, 70, 17);

        Tele.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Tele.setForeground(new java.awt.Color(255, 255, 255));
        Tele.setText("Telefone:");
        getContentPane().add(Tele);
        Tele.setBounds(220, 350, 60, 17);

        Ema.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ema.setForeground(new java.awt.Color(255, 255, 255));
        Ema.setText("Email:");
        getContentPane().add(Ema);
        Ema.setBounds(220, 380, 70, 17);

        CPF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CPF.setForeground(new java.awt.Color(255, 255, 255));
        CPF.setText("CPF:");
        getContentPane().add(CPF);
        CPF.setBounds(220, 420, 50, 14);
        getContentPane().add(txtCPF);
        txtCPF.setBounds(320, 410, 140, 24);

        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(320, 140, 40, 24);
        getContentPane().add(txtNome);
        txtNome.setBounds(320, 170, 220, 24);
        getContentPane().add(txtDate);
        txtDate.setBounds(320, 200, 130, 24);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(320, 230, 270, 24);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(320, 260, 250, 24);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(320, 290, 130, 24);
        getContentPane().add(txtEstado);
        txtEstado.setBounds(320, 320, 40, 24);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(320, 350, 140, 24);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(320, 380, 180, 24);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultset_previous.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 470, 50, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultset_first.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(90, 470, 50, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultset_next.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(210, 470, 50, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultset_last.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(270, 470, 50, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(560, 470, 46, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disk.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(600, 470, 46, 30);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application_form_magnify.png"))); // NOI18N
        getContentPane().add(jButton8);
        jButton8.setBounds(640, 470, 46, 30);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(703, 510, 40, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application_edit.png"))); // NOI18N
        getContentPane().add(jButton10);
        jButton10.setBounds(680, 470, 46, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application_delete.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(720, 470, 46, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retras.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-620, -20, 1450, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       String nome = txtNome.getText();
       String data_nasc = txtDate.getText();
       String telefone = txtTelefone.getText();
       String email = txtEmail.getText();  
       String bairro = txtBairro.getText();
       String estado = txtEstado.getText();
       String cidade = txtCidade.getText();
       String CPF = txtCPF.getText();
       String endereco = txtEndereco.getText();
       try{
           
           String insert_sql = "insert into tbfornecedores (nome, dt_nasc, telefone, email, bairro, estado, cidade, CPF, endereco) values('" + nome + "','"
                   + data_nasc + "','" + telefone + "','" + email + "','" + bairro + "','" + estado + "','" + cidade + "','" + CPF  + "','" + endereco + "')";
           
           con_forne.statement.executeUpdate(insert_sql);
           JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso");
           
           con_forne.resultset = con_forne.statement.executeQuery("Select * from tbfornecedores order by nome");
           con_forne.resultset.first();
           mostrarDados();
       } catch (SQLException errosql) {
           JOptionPane.showMessageDialog(null, "\nErro na gravação!\nERRO: " + errosql);
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       txtCodigo.setText("");
        txtNome.setText("");
         txtDate.setText("");
          txtTelefone.setText("");
           txtEmail.setText("");
            txtEndereco.setText("");
             txtCidade.setText("");
              txtEstado.setText("");
               txtBairro.setText("");
                txtCPF.setText("");
            txtNome.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                      try{
            con_forne.resultset.next();
            mostrarDados();
        } catch (SQLException erro){
            JOptionPane.showMessageDialog(null, "\nNão foi possível achar o registro\n" + erro);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                      try{
            con_forne.resultset.last();
            mostrarDados();
        } catch (SQLException erro){
            JOptionPane.showMessageDialog(null, "\nNão foi possível achar o registro\n" + erro);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                      try{
            con_forne.resultset.first();
            mostrarDados();
        } catch (SQLException erro){
            JOptionPane.showMessageDialog(null, "\nNão foi possível achar o registro\n" + erro);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                     try{
            con_forne.resultset.previous();
            mostrarDados();
        } catch (SQLException erro){
            JOptionPane.showMessageDialog(null, "\nNão foi possível achar o registro\n" + erro);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
               this.dispose();
            new Direct().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
              String sql = "";
       try{
           int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir mesmo?",
                   "confirmar exclusão", JOptionPane.YES_OPTION, 3);
           if (resposta == 0){
               sql = "delete from tbfornecedores where codigo = " + txtCodigo.getText();
               int excluir = con_forne.statement.executeUpdate(sql);
               if (excluir == 1){
                   JOptionPane.showMessageDialog(rootPane, "Exclusão realizada com sucesso");
                   con_forne.executaSQL("Select * from tbfornecedores order by codigo");
                   con_forne.resultset.first();
                   posicionarRegistro();
                   mostrarDados();
               }
           } else {
               JOptionPane.showMessageDialog(null, "\nOperação cancelada pelo usuário");
           }
       } catch (SQLException excecao) {
           JOptionPane.showMessageDialog(null, "\nErro de exclusão" + excecao
           + "\nComando SQL passado" + sql);
           
       }
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroForne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroForne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroForne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroForne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastroForne().setVisible(true);
            }
        });
    }
     public void mostrarDados(){
        try{
            txtCodigo.setText(con_forne.resultset.getString("codigo"));
            txtNome.setText(con_forne.resultset.getString("nome"));
            txtDate.setText(con_forne.resultset.getString("dt_nasc"));
            txtEndereco.setText(con_forne.resultset.getString("endereco"));
            txtBairro.setText(con_forne.resultset.getString("bairro"));
            txtCidade.setText(con_forne.resultset.getString("cidade"));
            txtEstado.setText(con_forne.resultset.getString("estado"));
            txtTelefone.setText(con_forne.resultset.getString("telefone"));
            txtEmail.setText(con_forne.resultset.getString("email"));
            txtCPF.setText(con_forne.resultset.getString("CPF"));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro.getMessage());
        }
    }
public void posicionarRegistro(){
        try{
            con_forne.resultset.first();
            mostrarDados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "\nNão foi possivel posicionar o primeiro registro\n"+erro);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairr;
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Cidad;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Ema;
    private javax.swing.JLabel End;
    private javax.swing.JLabel Estad;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Tele;
    private javax.swing.JLabel cod;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}


